Repository monizb/FireShort, pull requests merged in 2020-10, with the labels that each got.

#46 Feature password protection
  src/components/Admin.js
  src/components/Home.js
  src/components/ListUrls.js
Labels: CoreChanges

#51 Added Search functionality
  src/actions/filter.js
  src/actions/index.js
  src/actions/links.js
  src/components/Admin.js
  src/components/MainToolBar.js
  src/reducers/filter.js
  src/reducers/index.js
  src/reducers/links.js
  src/selectors/index.js
  src/selectors/selectors.js
Labels: CoreChanges

#56 Revert "Added Search functionality"
  src/actions/filter.js
  src/actions/index.js
  src/actions/links.js
  src/components/Admin.js
  src/components/MainToolBar.js
  src/reducers/filter.js
  src/reducers/index.js
  src/reducers/links.js
  src/selectors/index.js
  src/selectors/selectors.js
Labels: CoreChanges

#57 Added Search functionality again
  src/actions/filter.js
  src/actions/index.js
  src/actions/links.js
  src/components/Admin.js
  src/components/MainToolBar.js
  src/reducers/filter.js
  src/reducers/index.js
  src/reducers/links.js
  src/selectors/index.js
  src/selectors/selectors.js
Labels: CoreChanges

#69 removed password logger
  src/components/Home.js
Labels: CoreChanges, invalid

#66 Added the functionality to stop circular progressbar in login button in case of failed authentication
  src/components/Login.js
Labels: CoreChanges

#75 Fixes #41 Confirm dialog on URL delete event added
  src/components/Admin.js
Labels: CoreChanges

#78 Issue #74: Fixing the bug of hiding the loader
  src/components/Home.js
Labels: CoreChanges

#81 Implement Password Protection in Card Layout
  src/components/Admin.js
  src/components/CardUrls.js
Labels: CoreChanges

#94 Fixed Open Button For List Layout
  src/components/ListUrls.js
Labels: CoreChanges

#79 Signup feature, added pages: Signup.js, ForgotPassord.js, EmailNotVerified.js
  .gitignore
  firebase.json
  firestore.indexes.json
  firestore.rules
  src/App.js
  src/actions/auth.js
  src/components/Admin.js
  src/components/CardUrls.js
  src/components/EmailNotVerified.js
  src/components/ForgotPassword.js
  src/components/HitsDialog.js
  src/components/Home.js
  src/components/Login.js
  src/components/LoginLeftComponent.js
  src/components/ProtectedRoute.js
  src/components/Signup.js
  src/components/UrlsDialog.js
  src/config.js
  src/reducers/auth.js
Labels: CoreChanges

#103 Add tooltips to edit/remove/copy/preview/pwprotect buttons
  src/components/CardUrls.js
Labels: CoreChanges, invalid

#100 Issue #80: Adding space as a short url breaks the app (fix)
  src/components/UrlsDialog.js
Labels: CoreChanges

#85 moved action buttons into users intial view
  package.json
  src/components/Admin.js
  src/components/CardUrls.js
  src/components/ListUrls.js
Labels: CoreChanges

#119 Add protect link button switch
  src/components/Admin.js
  src/components/ListUrls.js
  src/components/UrlsDialog.js
Labels: CoreChanges

#120 Create analytics page
  package-lock.json
  package.json
  src/App.js
  src/components/Admin.js
  src/components/Analytics.js
  src/components/CardUrls.js
  src/components/EmailNotVerified.js
  src/components/Header.js
  src/components/HitsDialog.js
  src/components/Home.js
  src/components/ListUrls.js
Labels: CoreChanges, hacktoberfest-accepted

#135 Issue #117: Show a message when no links are available
  public/Images/pixeltrue-search.svg
  src/components/Admin.js
Labels: Assets, CoreChanges
